---

- hosts: all
  become: true
  pre_tasks:
    - name: installing epel-release
      tags: always
      package:
        name: epel-release
        state: latest

    - name: install updates
      tags: always
      package:
          update_only: yes
          update_cache: yes
          state: latest

- hosts: web_servers
  become: true
  tasks:
    - name: installing nginx
      package:
        name: nginx
        state: latest

- hosts: db_servers 
  become: true
  tasks: 
    - name: install mariadb server
      package:
        name: mariadb-server
        state: latest
        
